"""LLM client wrapper for Berget.ai (OpenAI-compatible) chat completions.

Provides helper functions for querying models with text or structured JSON schemas.
Includes fallback regex-style parsing to extract raw JSON block outputs if the
model wraps them in markdown backticks or prints leading conversational filler.
"""

from __future__ import annotations

import json
import os
from typing import Any

from .config import BERGET_BASE_URL
from .http import post_json


class VaneLlmError(RuntimeError):
    """Raised when LLM calls fail, API keys are missing, or responses are malformed."""


def chat_json(
    *,
    model: str,
    messages: list[dict[str, str]],
    temperature: float = 0.2,
    max_tokens: int = 4096,
) -> dict[str, Any]:
    """Execute a chat completion requiring a structured JSON object response.

    Args:
        model: The model string ID (e.g. Mistral Small).
        messages: A list of message dictionaries (system, user, assistant).
        temperature: Control parameter for creativity/sampling randomness.
        max_tokens: The upper limit on response token count.

    Returns:
        The parsed Python dictionary corresponding to the JSON response.

    Raises:
        VaneLlmError: If the API returns invalid format or the JSON is unparsable.
    """
    content = chat_text(
        model=model,
        messages=messages,
        temperature=temperature,
        max_tokens=max_tokens,
        response_format={"type": "json_object"},
    )
    return parse_json_object(content)


def chat_text(
    *,
    model: str,
    messages: list[dict[str, str]],
    temperature: float = 0.2,
    max_tokens: int = 4096,
    response_format: dict[str, Any] | None = None,
) -> str:
    """Execute a text-based chat completion query against the configured API base URL.

    Args:
        model: The model identifier to query.
        messages: A list of role/content dictionaries.
        temperature: LLM sampling temperature.
        max_tokens: Limit on generation tokens.
        response_format: Optional dict targeting output formats (e.g. {"type": "json_object"}).

    Returns:
        The raw string content generated by the model.

    Raises:
        VaneLlmError: If API credentials/URLs are missing or the API returns an error shape.
    """
    api_key = resolve_api_key()
    base_url = resolve_base_url().rstrip("/")
    payload: dict[str, Any] = {
        "model": model,
        "messages": messages,
        "temperature": temperature,
        "max_tokens": max_tokens,
    }
    if response_format:
        payload["response_format"] = response_format

    response = post_json(
        f"{base_url}/chat/completions",
        payload,
        {"Authorization": f"Bearer {api_key}"},
    )
    try:
        return response["choices"][0]["message"]["content"]
    except (KeyError, IndexError, TypeError) as error:
        raise VaneLlmError(f"Unexpected LLM response shape: {response}") from error


def resolve_api_key() -> str:
    """Resolve the API key from environment variables.

    Checks VANE_API_KEY, BERGET_API_KEY, and OPENAI_API_KEY in order of priority.

    Returns:
        The resolved API key string.

    Raises:
        VaneLlmError: If no environment variable is set.
    """
    api_key = os.getenv("VANE_API_KEY") or os.getenv("BERGET_API_KEY") or os.getenv("OPENAI_API_KEY")
    if not api_key:
        raise VaneLlmError("Missing API key. Set VANE_API_KEY, BERGET_API_KEY, or OPENAI_API_KEY.")
    return api_key


def resolve_base_url() -> str:
    """Resolve the endpoint base URL from environment variables or config defaults.

    Prioritizes VANE_BASE_URL, then BERGET_BASE_URL, then OPENAI_BASE_URL,
    defaulting to the hardcoded Berget URL.

    Returns:
        The resolved URL string.
    """
    return os.getenv("VANE_BASE_URL") or os.getenv("BERGET_BASE_URL") or os.getenv("OPENAI_BASE_URL") or BERGET_BASE_URL


def parse_json_object(content: str) -> dict[str, Any]:
    """Parse a string containing a JSON object, stripping markdown wrappers if present.

    Attempts standard JSON loading first. If it fails, falls back to scanning the string
    and extracting the boundaries of the first `{...}` block.

    Args:
        content: The raw text string containing JSON.

    Returns:
        The deserialized JSON dictionary.

    Raises:
        VaneLlmError: If no valid JSON object can be extracted or parsed.
    """
    cleaned = content.strip()
    # Strip markdown code block wrapping (e.g. ```json ... ```)
    if cleaned.startswith("```"):
        cleaned = cleaned.strip("`")
        if cleaned.lower().startswith("json"):
            cleaned = cleaned[4:].strip()
    try:
        parsed = json.loads(cleaned)
    except json.JSONDecodeError:
        # Fall back to matching brace boundaries if direct loading fails
        parsed = json.loads(extract_first_json_object(cleaned))
    if not isinstance(parsed, dict):
        raise VaneLlmError("Expected the model to return a JSON object.")
    return parsed


def strip_thinking(content: str) -> str:
    """Remove reasoning process segments bounded by <thinking>...</thinking> tags.

    Used when a reasoning model prints its scratchpad thoughts before returning JSON.

    Args:
        content: The raw text containing thinking tags.

    Returns:
        The text with all thinking tags and their internal content removed.
    """
    cleaned = content.strip()
    while "<thinking>" in cleaned and "</thinking>" in cleaned:
        before, rest = cleaned.split("<thinking>", 1)
        _, after = rest.split("</thinking>", 1)
        cleaned = f"{before}{after}".strip()
    return cleaned


def extract_first_json_object(content: str) -> str:
    """Extract the first valid matching curly-brace JSON block from a string.

    Tracks brace depth and ignores braces embedded within string literals.

    Args:
        content: The raw text string containing a JSON block.

    Returns:
        The extracted JSON object substring.

    Raises:
        VaneLlmError: If no open brace is found or the braces are not closed.
    """
    start = content.find("{")
    if start < 0:
        raise VaneLlmError("No JSON object found in model output.")
    depth = 0
    in_string = False
    escape = False
    for index, char in enumerate(content[start:], start=start):
        if in_string:
            if escape:
                escape = False
            elif char == "\\":
                escape = True
            elif char == '"':
                in_string = False
            continue
        if char == '"':
            in_string = True
        elif char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return content[start : index + 1]
    raise VaneLlmError("JSON object in model output was not closed.")
